wdbc<-read.table(file.choose(),sep=',')
wdbc
wdbc<-wdbc[,-1]
summary(wdbc)
data_norm<-function(x){((x-min(x))/(max(x)-min(x)))}
wdbc_norm<-as.data.frame(lapply(wdbc[,-1],data_norm))
wdbc_norm
View(wdbc_norm)
wdbc_train<-wdbc_norm[1:30,]
wdbc_train
wdbc_test<-wdbc_norm[31:60,]
wdbc_test
wdbc_pred<-knn(wdbc_train,wdbc_test,wdbc[31:60,1],k=1)
wdbc_pred
table(wdbc_pred,wdbc[31:60,1])
wdbc1<-table(wdbc_pred,wdbc[31:60,1])
sum(diag(wdbc1))
sum(wdbc1)
accuracy=(sum(diag(wdbc1))/sum(wdbc1))
accuracy

